services:
  covid_data_collector:
    build: .
    container_name: covid_data_collector
    volumes:
      - ./scripts:/app/scripts
      - ./logs:/app/logs
      - ./data:/app/databases
    restart: always
    environment:
      - http_proxy=http://localhost:80
      - https_proxy=http://localhost:80
      - no_proxy=localhost,127.0.0.1,api.covid19api.com,www.ebi.ac.uk
    networks:
      - backend_network
    extra_hosts:
      - "www.ebi.ac.uk:0.0.0.0"
    command: ["cron", "-f"]

networks:
  backend_network:
    driver: bridge
