services:
  backend:
    build: ./backend
    container_name: node_backend
    restart: always
    environment:
      - NODE_ENV=${NODE_ENV}
      - BACKEND_HOST_URL=${BACKEND_HOST_URL}
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./data:/app/data
    ports:
      - "3000:3000"

  nginx:
    build: ./nginx
    container_name: nginx_proxy
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - backend

  covid_data_collector:
    build: .
    container_name: covid_data_collector
    volumes:
      - ./scripts:/app/scripts
      - ./logs:/app/logs
      - ./data:/app/databases
    restart: always
    environment:
      - http_proxy=http://localhost:80
      - https_proxy=http://localhost:80
      - no_proxy=localhost,127.0.0.1,api.covid19api.com,www.ebi.ac.uk
    # networks:
    #   - backend_network
    extra_hosts:
      - "www.ebi.ac.uk:0.0.0.0"
    command: ["cron", "-f"]
