services:
  backend:
    build: ./backend
    container_name: node_backend
    restart: always
    environment:
      - NODE_ENV=${NODE_ENV}
      - BACKEND_HOST_URL=${BACKEND_HOST_URL}
    volumes:
      - ./data:/app/data
      - ./backend/subscribers.txt:/app/subscribers.txt
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_BACKEND_HOST_URL: ${VITE_BACKEND_HOST_URL}
    container_name: vite_frontend
    restart: always
    environment:
      - NODE_ENV=${NODE_ENV}
      - VITE_BACKEND_HOST_URL=${BACKEND_HOST_URL}
    ports:
      - "8000:80"
    depends_on:
      - backend

  covid_data_collector:
    build: .
    container_name: covid_data_collector
    volumes:
      - ./logs:/app/logs
      - ./data:/app/databases
      - ./raw_data:/app/raw_data
      - ./scripts:/app/scripts
    restart: always
    environment:
      - SPRINGER_API_KEY=${SPRINGER_API_KEY}
      - http_proxy=http://localhost:80
      - https_proxy=https://localhost:80
      - HTTP_PROXY=http://localhost:80
      - HTTPS_PROXY=https://localhost:80
      - no_proxy=localhost,127.0.0.1,api.covid19api.com,www.ebi.ac.uk,eutils.ncbi.nlm.nih.gov,doaj.org,api.springernature.com
    network_mode: host
    command: [ "cron", "-f" ]
